name: Settings For Action
description: A GitHub Action to get settings for action from json file
inputs:
  settings_path:
    description: the path of settings file
    required: true
outputs:
  PicBed:
    description: pic bed
  UseWebhook:
    description: if use webhook
  DbInit:
    description: if db init
  PageSize:
    description: page size of tweets
  SettingsPath:
    description: the path of settings file
runs:
  using: node12
  main: dist/index.js
