name: github pages

on:
  push:
    branches:
      - main
    paths:
      - 'vue-twitter/**'
  watch:
    types: started

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: |
          cd vue-twitter
          npm install
      - run: |
          cd vue-twitter
          npm run build

      - run: |
          cp -r ${{ github.workspace }}/twitter-json/raw/twitter ${{ github.workspace }}/vue-twitter/dist
        
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vue-twitter/dist