name: github pages

on:
  watch:
    types: started

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: |
          cd vue-twitter
          npm instatll
      - run: |
          cd vue-twitter
          npm run build
        

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vue-twitter/dist