name: Go
on:
  # push:
  # pull_request:
  # schedule:
  #   - cron:  '0 5 * * *'
  watch:
    types: started

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    env:
      TZ: Asia/Shanghai

    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Git pull
      run:  |
        git config --local user.email "larch.liu@gmail.com"
        git config --local user.name "Alex.Liu"
        git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git pull

    - name: Get dependencies
      run: |
        cd twitter-json
        go get -v -t -d ./...

    - name: Go run
      run: |
        cd twitter-json
        go run tweets.go

    - name: Git push
      run: |
        git add .
        git commit -m "update by github action"
        git push

    - name: push to gh-page branch
      run: |
        git clone --depth=1 --single-branch --branch gh-pages https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} /home/runner/gh-page
        copy /home/runner/work/gh-twitter/gh-twitter/twitter-json/raw/twitter to /home/runner/gh-page
        git config --local user.email "larch.liu@gmail.com"
        git config --local user.name "Alex.Liu"
        git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add .
        git commit -m "update by github action"
        git push
