name: twitter scraper
on:
  # schedule:
  #   - cron: "0 0/4 * * *"
  repository_dispatch:
    types: [scraper, addusers, delusers]
  workflow_dispatch:

jobs:
  cancel_previous:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.cancel_check.outputs.should_skip }}
    steps:
      - name: Cancel Previous Runs Actions
        id: cancel_check
        uses: LarchLiu/cancel_previous_runs@V1.1.0
        with:
          cancel_previous: "true"

  scraper:
    needs: cancel_previous
    if: ${{ needs.cancel_previous.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      # - name: MongoDB in GitHub Actions
      #   uses: supercharge/mongodb-github-action@1.3.0

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get settings
        id: settings
        uses: ./actions/get-settings-action
        with:
          settings_path: settings.json

      # - name: Import db to mongodb
      #   if: ${{ steps.settings.outputs.DbInit == 'true' }}
      #   run: |
      #     mongoimport -h localhost:27017 -d twitter -c profile ./twitter-json/raw/mongodb/profile.json
      #     mongoimport -h localhost:27017 -d twitter -c images ./twitter-json/raw/mongodb/images.json
      #     mongoimport -h localhost:27017 -d twitter -c tweets ./twitter-json/raw/mongodb/tweets.json

      - name: Get dependencies
        run: go get -v -t -d ./...
        working-directory: twitter-json

      - name: Change users and run scraper
        if: ${{ github.event.action == 'addusers' || github.event.action == 'delusers' }}
        run: go run main.go
        working-directory: twitter-json
        env:
          PIC_BED: ${{ steps.settings.outputs.PicBed }}
          DB_INIT: ${{ steps.settings.outputs.DbInit }}
          USE_WEBHOOK: ${{ steps.settings.outputs.UseWebhook }}
          PAGE_SIZE: ${{ steps.settings.outputs.PageSize }}
          SETTINGS_PATH: ${{ steps.settings.outputs.SettingsPath }}
          EVENT_TYPE: ${{ github.event.action }}
          USERS_DATA: ${{ github.event.client_payload.users }}
          QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
          QINIU_BUCKET: ${{ secrets.QINIU_BUCKET }}
          QINIU_DOMAIN: ${{ secrets.QINIU_DOMAIN }}
          QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
          QINIU_RESOURCE_PREFIX: ${{ secrets.QINIU_RESOURCE_PREFIX }}
          SMMS_TOKEN: ${{ secrets.SMMS_TOKEN }}
          CF_WORKERS_VIDEO_DOMAIN: ${{ secrets.CF_WORKERS_VIDEO_DOMAIN }}
          CF_WORKERS_IMG_DOMAIN: ${{ secrets.CF_WORKERS_IMG_DOMAIN }}
          MONGODB_CLOUD_URI: ${{ secrets.MONGODB_CLOUD_URI }}

      - name: Run scraper
        if: ${{ !(github.event.action=='addusers' || github.event.action=='delusers') }}
        run: go run main.go
        working-directory: twitter-json
        env:
          PIC_BED: ${{ steps.settings.outputs.PicBed }}
          DB_INIT: ${{ steps.settings.outputs.DbInit }}
          USE_WEBHOOK: ${{ steps.settings.outputs.UseWebhook }}
          PAGE_SIZE: ${{ steps.settings.outputs.PageSize }}
          SETTINGS_PATH: ${{ steps.settings.outputs.SettingsPath }}
          QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
          QINIU_BUCKET: ${{ secrets.QINIU_BUCKET }}
          QINIU_DOMAIN: ${{ secrets.QINIU_DOMAIN }}
          QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
          QINIU_RESOURCE_PREFIX: ${{ secrets.QINIU_RESOURCE_PREFIX }}
          SMMS_TOKEN: ${{ secrets.SMMS_TOKEN }}
          CF_WORKERS_VIDEO_DOMAIN: ${{ secrets.CF_WORKERS_VIDEO_DOMAIN }}
          CF_WORKERS_IMG_DOMAIN: ${{ secrets.CF_WORKERS_IMG_DOMAIN }}
          MONGODB_CLOUD_URI: ${{ secrets.MONGODB_CLOUD_URI }}

      # - name: Export mongodb
      #   run: |
      #     mongoexport -h localhost:27017 -d twitter -c profile -o ./twitter-json/raw/mongodb/profile.json
      #     mongoexport -h localhost:27017 -d twitter -c images -o ./twitter-json/raw/mongodb/images.json
      #     mongoexport -h localhost:27017 -d twitter -c tweets -o ./twitter-json/raw/mongodb/tweets.json

      - name: Git push
        run: |
          git config --local user.email ${{ github.actor }}@users.noreply.github.com
          git config --local user.name ${{ github.actor }}
          git add .
          git commit -m "update by github action"
          git push

      - name: push to gh-page branch
        run: |
          git clone --depth=1 --single-branch --branch gh-pages https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} /home/runner/gh-page
          cp -r ${{ github.workspace }}/twitter-json/raw/twitter /home/runner/gh-page
          cd /home/runner/gh-page
          git config --local user.email ${{ github.actor }}@users.noreply.github.com
          git config --local user.name ${{ github.actor }}
          git add .
          git commit --allow-empty -m "update by twitter scraper"
          git push
